version: '2'
services: 
    postgis :
        build: .
        container_name: gis_loader
        environment: 
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=peidevs
        volumes: 
            - ./data:/home/workspace/data
        ports: 
            - "5432:5432"